export const CREATE_LOAN_REQUEST = 'CREATE_LOAN_REQUEST'
export const CREATE_LOAN_SUCCESS = 'CREATE_LOAN_SUCCESS'
export const CREATE_LOAN_FAIL = 'CREATE_LOAN_FAIL'
export const CREATE_LOAN_RESET = 'CREATE_LOAN_RESET'


export const LIST_LOAN_REQUEST = 'LIST_LOAN_REQUEST'
export const LIST_LOAN_SUCCESS = 'LIST_LOAN_SUCCESS'
export const LIST_LOAN_FAIL = 'LIST_LOAN_FAIL'
export const LIST_LOAN_RESET = 'LIST_LOAN_RESET'

export const DELETE_LOAN_REQUEST = 'DELETE_LOAN_REQUEST'
export const DELETE_LOAN_SUCCESS = 'DELETE_LOAN_SUCCESS'
export const DELETE_LOAN_FAIL = 'DELETE_LOAN_FAIL'

export const UPDATE_LOAN_REQUEST = 'UPDATE_LOAN_REQUEST'
export const UPDATE_LOAN_SUCCESS = 'UPDATE_LOAN_SUCCESS'
export const UPDATE_LOAN_FAIL = 'UPDATE_LOAN_FAIL'
export const UPDATE_LOAN_RESET = 'UPDATE_LOAN_RESET'


export const DETAILS_LOAN_REQUEST = 'DETAILS_LOAN_REQUEST'
export const DETAILS_LOAN_SUCCESS = 'DETAILS_LOAN_SUCCESS'
export const DETAILS_LOAN_FAIL = 'DETAILS_LOAN_FAIL'