export const MEMBER_CREATE_REQUEST = 'MEMBER_CREATE_REQUEST'
export const MEMBER_CREATE_SUCCESS = 'MEMBER_CREATE_SUCCESS'
export const MEMBER_CREATE_FAIL = 'MEMBER_CREATE_FAIL'
export const MEMBER_CREATE_RESET = 'MEMBER_CREATE_RESET'


export const LIST_MEMBER_REQUEST = 'LIST_MEMBER_REQUEST'
export const LIST_MEMBER_SUCCESS = 'LIST_MEMBER_SUCCESS'
export const LIST_MEMBER_FAIL = 'LIST_MEMBER_FAIL'
export const LIST_MEMBER_RESET = 'LIST_MEMBER_RESET'

export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST'
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS'
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL'

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST'
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS'
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL'
export const MEMBER_UPDATE_RESET = 'MEMBER_UPDATE_RESET'


export const MEMBER_DETAILS_REQUEST = 'MEMBER_DETAILS_REQUEST'
export const MEMBER_DETAILS_SUCCESS = 'MEMBER_DETAILS_SUCCESS'
export const MEMBER_DETAILS_FAIL = 'MEMBER_DETAILS_FAIL'