export const CREATE_SAVINGS_REQUEST = 'CREATE_SAVINGS_REQUEST'
export const CREATE_SAVINGS_SUCCESS = 'CREATE_SAVINGS_SUCCESS'
export const CREATE_SAVINGS_FAIL = 'CREATE_SAVINGS_FAIL'
export const CREATE_SAVINGS_RESET = 'CREATE_SAVINGS_RESET'


export const LIST_SAVINGS_REQUEST = 'LIST_SAVINGS_REQUEST'
export const LIST_SAVINGS_SUCCESS = 'LIST_SAVINGS_SUCCESS'
export const LIST_SAVINGS_FAIL = 'LIST_SAVINGS_FAIL'
export const LIST_SAVINGS_RESET = 'LIST_SAVINGS_RESET'

export const DELETE_SAVINGS_REQUEST = 'DELETE_SAVINGS_REQUEST'
export const DELETE_SAVINGS_SUCCESS = 'DELETE_SAVINGS_SUCCESS'
export const DELETE_SAVINGS_FAIL = 'DELETE_SAVINGS_FAIL'

export const UPDATE_SAVINGS_REQUEST = 'UPDATE_SAVINGS_REQUEST'
export const UPDATE_SAVINGS_SUCCESS = 'UPDATE_SAVINGS_SUCCESS'
export const UPDATE_SAVINGS_FAIL = 'UPDATE_SAVINGS_FAIL'
export const UPDATE_SAVINGS_RESET = 'UPDATE_SAVINGS_RESET'


export const DETAILS_SAVINGS_REQUEST = 'DETAILS_SAVINGS_REQUEST'
export const DETAILS_SAVINGS_SUCCESS = 'DETAILS_SAVINGS_SUCCESS'
export const DETAILS_SAVINGS_FAIL = 'DETAILS_SAVINGS_FAIL'